//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاي دسترسي.
        /// </summary>
        internal static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند الصاق شده موجود نمي باشد.
        /// </summary>
        internal static string AccessConfirmation {
            get {
                return ResourceManager.GetString("AccessConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیان گیری.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا قصد پشتیبان گیری دارید؟.
        /// </summary>
        internal static string BackupConfirmation {
            get {
                return ResourceManager.GetString("BackupConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از تغییر کاربر اطمینان دارید؟.
        /// </summary>
        internal static string ChangeConfirmation {
            get {
                return ResourceManager.GetString("ChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        internal static string CreateButtonText {
            get {
                return ResourceManager.GetString("CreateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        internal static string Dangerous {
            get {
                return ResourceManager.GetString("Dangerous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیمار دارای بیماری(های) خطرناک می باشد.
        /// </summary>
        internal static string DangerousConfirmation {
            get {
                return ResourceManager.GetString("DangerousConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف اطمینان دارید؟.
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ انتخاب شده برای این دندان در پایگاه داده موجود نمی باشد.
        /// </summary>
        internal static string DeletedColor {
            get {
                return ResourceManager.GetString("DeletedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از خارج شدن اطمینان دارید؟.
        /// </summary>
        internal static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور جدید، باید با تایید کلمه عبور مطابقت داشته باشد.
        /// </summary>
        internal static string IncorrectNewPassword {
            get {
                return ResourceManager.GetString("IncorrectNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور قبلی اشتباه است..
        /// </summary>
        internal static string IncorrectOldPassword {
            get {
                return ResourceManager.GetString("IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربر و یا کلمه عبور اشتباه می باشد.
        /// </summary>
        internal static string IncorrectUser {
            get {
                return ResourceManager.GetString("IncorrectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايجاد.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول کلمه عبور جدید حداقل باید 5 کاراکتر باشد.
        /// </summary>
        internal static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کاربر بدون کلمه عبور قبلی امکان پذیر نیست.
        /// </summary>
        internal static string OldPasswordCanNotBeNull {
            get {
                return ResourceManager.GetString("OldPasswordCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کاربر بدون کلمه عبور امکان پذیر نیست.
        /// </summary>
        internal static string PasswordCanNotBeNull {
            get {
                return ResourceManager.GetString("PasswordCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       .کلمه عبور تغییر کرد         .
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر کلمه عبور.
        /// </summary>
        internal static string PasswordChangedTitle {
            get {
                return ResourceManager.GetString("PasswordChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از اعمال تغییرات اطمینان دارید؟.
        /// </summary>
        internal static string SettingConfirmMessage {
            get {
                return ResourceManager.GetString("SettingConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات مورد نظر با موفقیت صورت گرفت.
        /// </summary>
        internal static string Successed {
            get {
                return ResourceManager.GetString("Successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تهیه نسخه پشتیبان با موفقیت صورت گرفت.
        /// </summary>
        internal static string SuccessFullBackup {
            get {
                return ResourceManager.GetString("SuccessFullBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگرداندن نسخه پشتیبان با موفقیت صورت گرفت.
        /// </summary>
        internal static string SuccessFullRestoreBackup {
            get {
                return ResourceManager.GetString("SuccessFullRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويرايش.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از اعمال تغییرات اطمینان دارید؟.
        /// </summary>
        internal static string UpdateConfirmation {
            get {
                return ResourceManager.GetString("UpdateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات بروز رسانی با موفقیت انجام شد.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری مورد نظر  Lock  می باشد، لطفا با مدیر سیستم تماس بگیرید..
        /// </summary>
        internal static string UserIsLock {
            get {
                return ResourceManager.GetString("UserIsLock", resourceCulture);
            }
        }
    }
}
