using System;
using System.Collections.Generic;
using System.Text;

namespace DataObjectLayer
{
    public class DoctorDOL
    {
        public const string Select = @"SELECT DOCTOR.DOCTORID, DOCTOR.FIRSTNAME, DOCTOR.LASTNAME, DOCTOR.GENDER, DOCTOR.DOCTORCODE, DOCTOR.MEDICALCODE, DOCTOR.SPECIALISTID, SPECIALIST.SPECIALISTTITLE FROM DOCTOR INNER JOIN SPECIALIST ON DOCTOR.SPECIALISTID = SPECIALIST.SPECIALISTID";
        public const string Insert = @"INSERT INTO DOCTOR( FIRSTNAME, LASTNAME, GENDER, DOCTORCODE, MEDICALCODE, SPECIALISTID) VALUES( @FIRSTNAME, @LASTNAME, @GENDER, @DOCTORCODE, @MEDICALCODE, @SPECIALISTID)";        
        public const string Delete = "DELETE FROM DOCTOR WHERE DOCTORID=@DoctorId";
        public const string Update = "UPDATE DOCTOR SET FIRSTNAME = @FIRSTNAME, LASTNAME = @LASTNAME, GENDER = @GENDER, DOCTORCODE = @DOCTORCODE, MEDICALCODE = @MEDICALCODE, SPECIALISTID = @SPECIALISTID WHERE DOCTORID = @DoctorId";
        public const string SelectMaxId = "SELECT ISNULL(MAX(DOCTORID),0)+1 AS MAX_DOCTOR_ID FROM DOCTOR";
        public enum QueryStatus { Select, Insert, Delete, Update, SelectMaxId };
    }
}
