using System;
using System.Collections.Generic;
using System.Text;

namespace DataObjectLayer
{
    public class EquipmentHistoryDOL
    {
        public const string Select = @"SELECT EQUIPMENTHISTORYID,EQUIPMENTHISTORY.EQUIPMENTID, EQUIPMENTHISTORY.DATE, EQUIPMENTHISTORY.COUNT, EQUIPMENTHISTORY.ISINPUT, EQUIPMENT.EQUIPMENTTITLE FROM EQUIPMENTHISTORY INNER JOIN EQUIPMENT ON EQUIPMENTHISTORY.EQUIPMENTID = EQUIPMENT.EQUIPMENTID";
        public const string Insert = @"INSERT INTO EQUIPMENTHISTORY (EQUIPMENTID, DATE, COUNT, ISINPUT) VALUES(@EQUIPMENTID, @DATE, @COUNT, @ISINPUT)";
        public const string Delete = "DELETE FROM EQUIPMENTHISTORY WHERE EQUIPMENTHISTORYID=@EQUIPMENTHISTORYID";
        public const string Update = "UPDATE EQUIPMENTHISTORY SET DATE = @DATE, COUNT = @COUNT, ISINPUT = @ISINPUT , EQUIPMENTID = @EQUIPMENTID WHERE  EQUIPMENTHISTORYID = @EQUIPMENTHISTORYID ";
        public const string SelectMaxId = "SELECT ISNULL(MAX(EQUIPMENTHISTORYID),0)+1 AS MAX_EQUIPMENTHISTORY_ID FROM EQUIPMENTHISTORY";
        public enum QueryStatus { Select, SelectByPatient, Insert, Delete, Update, SelectMaxId };
    }
}
