using System;
using System.Collections.Generic;
using System.Text;

namespace DataObjectLayer
{
    public class ServiceDOL
    {
        public const string Select = @"SELECT SERVICE.SERVICETYPEID, SERVICE.SERVICEID, SERVICE.PATIENTID, SERVICE.DISCOUNT, SERVICE.ISFINISHED, SERVICE.PRICE, SERVICETYPE.SERVICETYPETITLE, SERVICE.DATE , SERVICETYPE.ISLABORATORY FROM SERVICE INNER JOIN SERVICETYPE ON SERVICE.SERVICETYPEID = SERVICETYPE.SERVICETYPEID WHERE (SERVICE.PATIENTID = @PATIENTID)";
        public const string Insert = @"INSERT INTO SERVICE (SERVICETYPEID, PATIENTID, DISCOUNT,  DATE, PRICE) VALUES (@SERVICETYPEID, @PATIENTID, @DISCOUNT, @DATE,@PRICE)";
        public const string Delete = "DELETE FROM SERVICE WHERE SERVICEID=@SERVICEID";
        public const string Update = "UPDATE SERVICE SET SERVICETYPEID = @SERVICETYPEID, PATIENTID = @PATIENTID, DISCOUNT = @DISCOUNT, ISFINISHED = @ISFINISHED, DATE = @DATE , PRICE = @PRICE WHERE SERVICEID = @ServiceId";
        public const string SelectMaxId = "SELECT ISNULL(MAX(SERVICEID),0)+1 AS MAX_SERVICE_ID FROM SERVICE";    
        public enum QueryStatus { Select, Insert, Delete, Update, SelectMaxId};
    }
}
