using System;
using System.Collections.Generic;
using System.Text;

namespace DataObjectLayer
{
    public class ServiceTypeDOL
    {
        public const string Select = @"SELECT SERVICETYPEID, SERVICETYPETITLE, PRICE, SESSION, SERVICETYPECODE, NEXTREFRENCE , DESCRIPTION , ISLABORATORY FROM SERVICETYPE";
        public const string SelectComboBox = @"SELECT SERVICETYPEID, SERVICETYPETITLE FROM SERVICETYPE  UNION (SELECT ID AS SERVICETYPEID, TEXT AS SERVICETYPETITLE FROM NOSELECTION)";
        public const string SelectComboBoxByIsLaboratory = @"SELECT SERVICETYPEID, SERVICETYPETITLE FROM SERVICETYPE WHERE (ISLABORATORY = @ISLABORATORY OR  (@ISLABORATORY IS NULL))UNION (SELECT ID AS SERVICETYPEID, TEXT AS SERVICETYPETITLE FROM NOSELECTION)";        
        public const string Insert = @"INSERT INTO SERVICETYPE (SERVICETYPEID, SERVICETYPETITLE, PRICE, SESSION, SERVICETYPECODE, NEXTREFRENCE, DESCRIPTION , ISLABORATORY) VALUES(@SERVICETYPEID, @SERVICETYPETITLE, @PRICE, @SESSION, @SERVICETYPECODE, @NEXTREFRENCE ,@DESCRIPTION ,@ISLABORATORY)";
        public const string Delete = "DELETE FROM SERVICETYPE WHERE SERVICETYPEID=@SERVICETYPEID";
        public const string Update = "UPDATE SERVICETYPE SET SERVICETYPETITLE = @SERVICETYPETITLE, PRICE = @PRICE, SESSION = @SESSION, SERVICETYPECODE = @SERVICETYPECODE, NEXTREFRENCE = @NEXTREFRENCE , DESCRIPTION = @DESCRIPTION , ISLABORATORY = @ISLABORATORY WHERE SERVICETYPEID = @SERVICETYPEID";
        public const string SelectMaxId = "SELECT ISNULL(MAX(SERVICETYPEID),0)+1 AS MAX_SERVICETYPE_ID FROM SERVICETYPE";
        public const string SelectServiceTypePrice = "SELECT PRICE FROM SERVICETYPE WHERE SERVICETYPEID = @SERVICETYPEID";
        public enum QueryStatus { Select, SelectComboBox, Insert, Delete, Update, SelectMaxId, SelectComboBoxByIsLaboratory, SelectServiceTypePrice };
    }
}
